- biome: ocean
  maxAltitude: -26
- biome: ashlands
  minDistance: 0.8
  curveY: -0.4
- biome: mountain
  minAltitude: 50
- biome: deepnorth
  minDistance: 0.8
  curveY: 0.4
- biome: swamp
  maxAltitude: 20
  minAltitude: -20
  maxDistance: 0.6
  minDistance: 0.2
  amount: 0.4
  wiggleDistance: false
- biome: mistlands
  minDistance: 0.6
  amount: 0.6
- biome: plains
  maxDistance: 0.8
  minDistance: 0.3
  amount: 0.6
- biome: blackforest
  maxDistance: 0.6
  minDistance: 0.06
  amount: 0.6
- biome: meadows
  maxDistance: 0.5
- biome: deepforest
  minDistance: 0.6
  amount: 0.8
- biome: blackforest
