- biome: Meadows
  environments:
  - environment: Clear
    weight: 5
  - environment: Rain
    weight: 0.2
  - environment: Misty
    weight: 0.2
  - environment: ThunderStorm
    weight: 0.2
  - environment: LightRain
    weight: 0.2
  mapColor:
    r: 0.573
    g: 0.655
    b: 0.361
    a: 1
  musicDay: meadows
- biome: BlackForest
  environments:
  - environment: DeepForest Mist
    weight: 2
  - environment: Rain
    weight: 0.1
  - environment: Misty
    weight: 0.1
  - environment: ThunderStorm
    weight: 0.1
  color:
    b: 1
  mapColor:
    r: 0.42
    g: 0.455
    b: 0.247
    a: 1
  musicDay: blackforest
  musicNight: blackforest
- biome: Swamp
  environments:
  - environment: SwampRain
  color:
    r: 1
  mapColor:
    r: 0.639
    g: 0.447
    b: 0.345
    a: 1
  musicDay: swamp
  musicNight: swamp
- biome: Mountain
  environments:
  - environment: SnowStorm
  - environment: Snow
    weight: 5
  color:
    g: 1
  mapColor:
    r: 1
    g: 1
    b: 1
    a: 1
  musicDay: mountain
  musicNight: mountain
- biome: DeepNorth
  environments:
  - environment: Twilight_SnowStorm
    weight: 0.5
  - environment: Twilight_Snow
  - environment: Twilight_Clear
  color:
    g: 1
  mapColor:
    r: 1
    g: 1
    b: 1
    a: 1
- biome: Plains
  environments:
  - environment: Heath clear
    weight: 2
  - environment: Misty
    weight: 0.4
  - environment: LightRain
    weight: 0.4
  color:
    a: 1
  mapColor:
    r: 0.906
    g: 0.671
    b: 0.47
    a: 1
  musicDay: plains
  musicNight: plains
- biome: AshLands
  environments:
  - environment: Ashrain
  color:
    r: 1
    a: 1
  mapColorMultiplier: 0.5
  mapColor:
    r: 0.69
    g: 0.192
    b: 0.192
    a: 1
  musicDay: frostcaves
  musicNight: frostcaves
- biome: Ocean
  environments:
  - environment: Rain
    weight: 0.1
  - environment: LightRain
    weight: 0.1
  - environment: Misty
    weight: 0.1
  - environment: Clear
  - environment: ThunderStorm
    weight: 0.1
  mapColor:
    r: 1
    g: 1
    b: 1
    a: 1
- biome: Mistlands
  environments:
  - environment: Mistlands_clear
    weight: 1.5
  - environment: Mistlands_rain
    weight: 0.1
  - environment: Mistlands_thunder
    weight: 0.1
  color:
    b: 1
    a: 1
  mapColor:
    r: 0.2
    g: 0.2
    b: 0.2
    a: 1
  musicDay: mistlands
  musicNight: mistlands
- biome: deepforest
  name: DarkWoods
  terrain: BlackForest
  environments:
  - environment: DeepForest_Mist
    weight: 2
  - environment: DeepForest_Clear
    weight: 0.4
  - environment: DeepForest_thunder
    weight: 0.2
  color:
    b: 1
  mapColor:
    r: 0.2
    g: 0.22
    b: 0.12
    a: 1
  musicDay: boss_queen_ambience
  musicNight: boss_queen_ambience
