- prefab: SvartalfrQueenAltar_New
  biome: deepforest
  quantity: 3
  minAltitude: 1
  prioritized: true
  minDistanceFromSimilar: 4000
  maxTerrainDelta: 2
  exteriorRadius: 25
  clearArea: true
  noBuild: true
- prefab: Vegvisir_SvartalfrQueen
  biome: deepforest
  quantity: 35
  minAltitude: 1
  prioritized: true
  minDistanceFromSimilar: 1000
  maxTerrainDelta: 2
  exteriorRadius: 7
  clearArea: true
- prefab: JotunnAltar
  biome: DeepNorth
  quantity: 3
  minAltitude: 1
  prioritized: true
  minDistanceFromSimilar: 4000
  maxTerrainDelta: 2
  exteriorRadius: 25
  clearArea: true
  noBuild: true
- prefab: Vegvisir_Jotunn
  biome: DeepNorth
  quantity: 15
  minAltitude: 1
  prioritized: true
  minDistanceFromSimilar: 1000
  maxTerrainDelta: 2
  exteriorRadius: 6
  clearArea: true
- prefab: BlazingDamnedOneAltar
  biome: AshLands
  quantity: 3
  minAltitude: 1
  prioritized: true
  minDistanceFromSimilar: 4000
  maxTerrainDelta: 2
  exteriorRadius: 20
  clearArea: true
  noBuild: true
- prefab: Vegvisir_BlazingDamnedOne
  biome: AshLands
  quantity: 15
  minAltitude: 1
  prioritized: true
  minDistanceFromSimilar: 1000
  maxTerrainDelta: 2
  exteriorRadius: 4
  clearArea: true
- prefab: StaminaGreydwarf
  biome: Meadows
  quantity: 15
  minAltitude: 1
  prioritized: true
  minDistanceFromSimilar: 150
  maxTerrainDelta: 2
  exteriorRadius: 10
  clearArea: true
- prefab: StaminaTroll
  biome: BlackForest
  quantity: 15
  minAltitude: 1
  maxAltitude: 8500
  prioritized: true
  minDistanceFromSimilar: 150
  maxTerrainDelta: 2
  exteriorRadius: 10
  clearArea: true
- prefab: StaminaWraith
  biome: Swamp
  quantity: 15
  minAltitude: 1
  maxAltitude: 8500
  prioritized: true
  minDistanceFromSimilar: 150
  maxTerrainDelta: 2
  exteriorRadius: 10
  clearArea: true