- prefab: HeavymetalVein
  max: 1
  biome: deepforest
  minAltitude: 5
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groupRadius: 25
- prefab: FrometalVein_frac
  max: 1
  biome: DeepNorth
  minAltitude: 5
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groupRadius: 25
- prefab: BurningTree
  max: 2
  scaleMin: 0.8
  scaleMax: 1.2
  biome: AshLands
  minAltitude: 5
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  inForest: true
  forestTresholdMax: 0.75
  groupSizeMax: 2
  groupRadius: 60